alertmanager:
    enabled: false
prometheus:
    prometheusSpec:
        serviceMonitorNamespaceSelector:
            matchLabels:
                monitor: "true"
        podMonitorNamespaceSelector:
            matchLabels:
                monitor: "true"
    ingress:
        enabled: false
grafana:
    admin:
        existingSecret: grafana-admin
    dashboards:
        default:
            ceph-cluster:
                gnetId: 2842
                revision: 11
                datasource: Prometheus
            ceph-osd:
                gnetId: 5336
                revision: 3
                datasource: Prometheus
            ceph-pools:
                gnetId: 5342
                revision: 3
                datasource: Prometheus
    ingress:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            external-dns.alpha.kubernetes.io/hostname: grafana.kels.in
        hosts:
            - grafana.kels.in
        tls:
            - secretName: grafana-server-tls
              hosts:
                  - grafana.kels.in
