alertmanager:
    enabled: false
prometheus:
    ingress:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            external-dns.alpha.kubernetes.io/hostname: prometheus.kels.in
            nginx.ingress.kubernetes.io/auth-type: basic
            nginx.ingress.kubernetes.io/auth-secret: admin
            nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - kels.in'
        hosts:
            - prometheus.kels.in
        tls:
            - secretName: prometheus-server-tls
              hosts:
                  - prometheus.kels.in
grafana:
    admin:
        existingSecret: admin
    dashboards:
        default:
            ceph-cluster:
                gnetId: 2842
                revision: 11
            ceph-osd:
                gnetId: 5336
                revision: 3
                prometheus: Prometheus
            ceph-pools:
                gnetId: 5342
                revision: 3
                prometheus: Prometheus
            cert-manager:
                gnetId: 11001
                revision: 1
    ingress:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            external-dns.alpha.kubernetes.io/hostname: grafana.kels.in
        hosts:
            - grafana.kels.in
        tls:
            - secretName: grafana-server-tls
              hosts:
                  - grafana.kels.in
