alertmanager:
    enabled: false
prometheus:
    prometheusSpec:
        podMonitorNamespaceSelector: {}
        podMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        serviceMonitorSelector: {}
    ingress:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            external-dns.alpha.kubernetes.io/hostname: prometheus.kels.in
            external-dns.alpha.kubernetes.io/target: kels.in
            nginx.ingress.kubernetes.io/auth-type: basic
            nginx.ingress.kubernetes.io/auth-secret: admin
            nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - kels.in'
        hosts:
            - prometheus.kels.in
        tls:
            - secretName: prometheus-server-tls
              hosts:
                  - prometheus.kels.in
grafana:
    admin:
        existingSecret: admin
    dashboardProviders:
        dashboardproviders.yaml:
            apiVersion: 1
            providers:
                - name: default
                  orgId: 1
                  folder: ""
                  type: file
                  disableDeletion: true
                  editable: true
                  options:
                      path: /var/lib/grafana/dashboards/default
    dashboards:
        default:
            ceph-cluster:
                gnetId: 2842
                revision: 11
            ceph-osd:
                gnetId: 5336
                revision: 3
                prometheus: Prometheus
            ceph-pools:
                gnetId: 5342
                revision: 3
                prometheus: Prometheus
            cert-manager:
                gnetId: 11001
                revision: 1
    ingress:
        enabled: true
        annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            external-dns.alpha.kubernetes.io/hostname: grafana.kels.in
            external-dns.alpha.kubernetes.io/target: kels.in
        hosts:
            - grafana.kels.in
        tls:
            - secretName: grafana-server-tls
              hosts:
                  - grafana.kels.in
