rbac:
    create: true
controller:
    metrics:
        enabled: true
        serviceMonitor:
            enabled: true
    service:
        type: LoadBalancer
        externalTrafficPolicy: Local
    publishService:
        enabled: true
defaultBackend:
    enabled: false
